### PR TITLE
Feat/bicep health endpoint

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

* Adjustments to set health endpoint
*  Fixes for deployment in free plan (`alwaysOn` and `worker32bit` settings)
* Closes issue #34 for bicep based IaC

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code

```
Variant A: Execute `azd provision` or `azd up` as is
Varaiant B: Change the `skuName` in `main.bicep` to `B1`
```

## What to Check
Verify that the following are valid

* The deployment must be successfully executed
* The deployment is successfully executed, the health endpoint is set  

## Other Information

In the default plan for our setup (`F1`) the health endpoint cannot be enabled

The PR also contains several fixes for the setup of an app service with free plan concerning the limitations towards 32bit worker and alwaysOn setting.

### CODE REVIEW

**Comment by lechnerc77** [comment]
As some changes require a local modified copy of the `azd` core modules, I opened PRs that would sync the change to the `azd` core templates:

* <https://github.com/Azure/azure-dev/pull/1497>

If accepted and merged, we can remove our local copy of the modules.

**Comment by MartinPankraz** [comment]
@lechnerc77 quick plausability check: there are changes for free-plan compatability, but F1 isn't covering health endpoints anyways. Opportunity to simplify the template then and mark in readme only?

**Comment by lechnerc77** [comment]
> @lechnerc77 quick plausibility check: there are changes for free-plan compatibility, but F1 isn't covering health endpoints anyways. Opportunity to simplify the template then and mark in readme only?

We can eliminate some parameters in the bicep files but:

* They are defaulted and optional anyway
* They make life easier in case the template shall be transferred to a more realistic setup

So I would leave it as is, as for the free plan things work and the parameters would not add any cognitive load as no need to explicitly set them.

**Review by MartinPankraz — APPROVED** [review]
approved

**Pull request merged**
