### PR TITLE
Issue 46 - Compatibility with SAP Cloud SDK V3

### LINKED ISSUE #46: [FEATURE]: Upgrade to SAP Cloud SDK v3
### What area do you want to see improved?

app code

### Is your feature request related to a problem? Please describe.

SAP Cloud SDK released v3 recently. Make sure breaking changes described [here](https://github.com/SAP/cloud-sdk-js/blob/main/V3-Upgrade-Guide.md) are taken care of. V2 has maintenance for security for 6 months.

Additional upgrade docs: https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3

### Describe the solution you'd like

Whole project using SAP Cloud SDK v3

### Describe alternatives you've considered

None applicable

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lechnerc77**
## Purpose

* This PR provides the code adjustments to get compatibility with the SAP Cloud SDK V3
* Fixes #46 

## Does this introduce a breaking change?

```
[X] Yes - Node.js 18 is now prerequisite
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[X] Other... Please describe: Compatibility Adjustements
```

## How to Test

* Test the code

Local:
```
- Do an npm ci && bpm run build
- Execute locally via npm run start:dev
```

Remote
```
- Do an npm ci && bpm run build
- Deploy to a CF environment
```

## What to Check
Verify that the following are valid

* All routes can be accessed and provide data 

## Other Information

n/a

### CODE REVIEW

**Comment by lechnerc77** [comment]
@MartinPankraz : I did not yet test the call to a "real" system.

**Comment by MartinPankraz** [comment]
Tested with Business Partner API from API business hub:

{"statusCode":500,"message":"Failed to get business partners- Cannot read properties of undefined (reading 'startsWith')"}

**Comment by MartinPankraz** [comment]
Looks like there are more things to be corrected than the lib version raise @lechnerc77 https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3#use-service-function-instead-of-api-constructor

I think we are better of re-generating the SDK for the business partner from scratch. Thoughts?

**Comment by lechnerc77** [comment]
> Looks like there are more things to be corrected than the lib version raise @lechnerc77 https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3#use-service-function-instead-of-api-constructor
> 
> I think we are better of re-generating the SDK for the business partner from scratch. Thoughts?

As far as I have seen this is optional. But we can for sure regenerate  to start from a clean starting point.

**Comment by lechnerc77** [comment]
Regeneration fails: <https://github.com/SAP/cloud-sdk-js/issues/3628>

**Review by MartinPankraz — APPROVED** [review]
upgrade tested with API business hub and internal SAP.

approved

**Pull request merged**
